name: first workflow
env:
  WORKFLOW_VAR: "This variable is declared at the workflow level"


on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps: 
     - name: firstjob Script
       shell: sh
       run: echo Hello World! This is the first job
     - name: Checkout
       uses: actions/checkout@v5.0.0
     - name: Print to Log
       id: print-to-log
       uses: actions/hello-world-javascript-action@main
       with: 
          who-to-greet: ${{ github.actor }}
     - name: time
       run: |
        echo "The time of the greeting was at: ${{ steps.print-to-log.outputs.time }}"
       
    

  secondjob:
    env:
      JOB_VAR: "This is a job variable"
    runs-on: ubuntu-latest
    needs: firstjob
    steps:
     - name: secondjob script
       shell: sh
       run:
        echo this is the second job
        echo and this is a multi-line script
     - name: environment variables
       env:
        STEP_VAR: "This variable is declared at the step level"
       run: |
        echo $WORKFLOW_VAR
        echo $JOB_VAR
        echo $STEP_VAR
        echo "The following is a secret: ${{ secrets.SOME_SECRET}}, of course, i cant tell you otherwise be secret"
        echo "The following are default environment variable"
        echo $GITHUB_ACTOR
        echo $GITHUB_JOB
        echo $GITHUB_REF
       
       
